### ISSUE TITLE
Add automated security scanning to CI pipeline

### ISSUE THREAD

**Issue by phrazzld** [phrazzld/hyperbolic-time-chamber#21]
## Problem
The project lacks automated security scanning, partially violating **Ruthless Automation** and **Comprehensive Security Automation** principles:
- No dependency vulnerability scanning
- No static security analysis
- No secret detection in pre-commit hooks
- Manual security reviews only

### 1. Dependency Vulnerability Scanning
- Add Swift dependency scanner to CI
- Check for known CVEs in dependencies
- Fail builds on high-severity vulnerabilities
- Regular automated dependency updates

### 2. Static Security Analysis
- Add SwiftLint security rules
- Scan for common vulnerabilities:
  - Hardcoded secrets
  - Unsafe data handling
  - Injection vulnerabilities
  - Insecure random number generation

### 3. Secret Detection
- Pre-commit hook for secret scanning
- Scan for:
  - API keys
  - Passwords
  - Private keys
  - Tokens
- Use tools like gitleaks or similar

### 4. Security in PR Validation
```yaml
# In .github/workflows/pr-validation.yml
- name: Security Scan
  run: |
    # Dependency vulnerabilities
    swift package audit
    
    # Static analysis
    swiftlint analyze --reporter json
    
    # Secret detection
    gitleaks detect --source .
```

### 5. Security Reporting
- Generate security reports in CI
- Track security metrics over time
- Alert on new vulnerabilities

## Implementation Tools
- **gitleaks**: Secret detection
- **SwiftLint**: Static analysis with security rules
- **swift-package-audit**: Dependency scanning (or similar)
- **GitHub Security**: Dependabot alerts

## Benefits
- Early detection of vulnerabilities
- Prevent secrets from entering codebase
- Automated security compliance
- Reduced security review burden

## Acceptance Criteria
- [ ] Secret detection in pre-commit hooks
- [ ] Dependency scanning in CI
- [ ] Static security analysis configured
- [ ] Security step in PR validation
- [ ] Documentation for security tools
- [ ] Zero false positives in normal development
